In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import f1_score
# from helpers import plot_confusion_matrix
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df.head()

,id,url,title,target
0,0,m.kp.md,"Экс-министр экономики Молдовы - главе МИДЭИ, ц...",False
1,1,www.kp.by,Эта песня стала известна многим телезрителям б...,False
2,2,fanserials.tv,Банши 4 сезон 2 серия Бремя красоты смотреть о...,False
3,3,colorbox.spb.ru,Не Беси Меня Картинки,False
4,4,tula-sport.ru,В Новомосковске сыграют следж-хоккеисты алекси...,False

In [2]:
train_df['k'] = ' '
train_df['u'] = train_df['url'].str.split('.')

def g(S):
    if S[0] == 'w' and S[2] == 'w':
        S = S[3:]
    return S

f = lambda x: g(' '.join(x["url"].split(".")))


train_df["disappointed"] = train_df.apply(f, axis=1)

train_df['gg'] = train_df[['disappointed', 'k', 'title', 'k', 'disappointed']].sum(axis = 1)


test_df['k'] = ' '
test_df["disappointed"] = test_df.apply(f, axis=1)

test_df['gg'] = test_df[['disappointed', 'k', 'title', 'k', 'disappointed']].sum(axis = 1)
test_df.head()

,id,url,title,k,disappointed,gg
0,135309,www.kommersant.ru,Шестой кассационный суд в Самаре начнет работу...,,kommersant ru,kommersant ru Шестой кассационный суд в Самар...
1,135310,urexpert.online,"Что такое индексация алиментов, кем и в каких ...",,urexpert online,urexpert online Что такое индексация алиментов...
2,135311,imperimeha.ru,Женщинам | Империя Меха - Part 12,,imperimeha ru,imperimeha ru Женщинам | Империя Меха - Part 1...
3,135312,national-porn.com,"Небритые, волосатые киски: Порно всех стран и ...",,national-porn com,"national-porn com Небритые, волосатые киски: П..."
4,135313,2gis.ru,67,,2gis ru,2gis ru 67 2gis ru

In [3]:
X_train = train_df["gg"].values  # На трейн значение тайтлов

X_test = test_df["gg"].values  # На тест значение тайтлов (то что нужно)
y_train = train_df["target"].astype(int).values  # На трейн значение целей в инт

In [4]:
vectorizer = CountVectorizer()

In [5]:
X_train_vectorized = vectorizer.fit_transform(X_train)

In [6]:
model = LogisticRegression(solver='liblinear', C = 65)
model.fit(
    X_train_vectorized,
    y_train
)

y_pred = model.predict_proba(
    X_train_vectorized
)[:, 1] >= 0.33
f1_score(y_train, y_pred)

0.9997906009752012

In [7]:


X_test_vectorized = vectorizer.transform(X_test)


test_df["target"] = (model.predict_proba(X_test_vectorized)[:, 1] >= 0.33).astype(bool)

test_df[["id", "target"]].to_csv("FINAL.csv", index=False)

In [8]:
look = pd.read_csv("FINAL.csv")

look.head(30)

        id  target
0   135309   False
1   135310   False
2   135311   False
3   135312    True
4   135313   False
5   135314   False
6   135315   False
7   135316   False
8   135317   False
9   135318   False
10  135319   False
11  135320    True
12  135321   False
13  135322   False
14  135323   False
15  135324   False
16  135325   False
17  135326    True
18  135327   False
19  135328   False
20  135329   False
21  135330   False
22  135331   False
23  135332   False
24  135333   False
25  135334   False
26  135335   False
27  135336   False
28  135337   False
29  135338   False